name: Greetings

on: 
  pull_request:
    branches:    
    - master        
jobs:
  greeting:
    name: Greetings
    runs-on: ubuntu-latest
    steps:
    - name: Print Hi 
      env:
        MY_VAR: Hi there!
      run: |
        echo $MY_VAR
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        pr-message: 'Thanks for making a pull request:'' first pr'
